// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Counters is an autogenerated mock type for the Counters type
type Counters struct {
	mock.Mock
}

// UpdateAndGetCounter provides a mock function with given fields: ctx, counter
func (_m *Counters) UpdateAndGetCounter(ctx context.Context, counter string) (int64, error) {
	ret := _m.Called(ctx, counter)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, counter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, counter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
