// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// CreateShortUrl provides a mock function with given fields: w, r
func (_m *Handler) CreateShortUrl(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DeleteShortUrl provides a mock function with given fields: w, r
func (_m *Handler) DeleteShortUrl(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAShortUrl provides a mock function with given fields: w, r
func (_m *Handler) GetAShortUrl(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAccessToken provides a mock function with given fields: w, r
func (_m *Handler) GetAccessToken(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAllShortUrl provides a mock function with given fields: w, r
func (_m *Handler) GetAllShortUrl(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetUser provides a mock function with given fields: w, r
func (_m *Handler) GetUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// HomeHandler provides a mock function with given fields: w, r
func (_m *Handler) HomeHandler(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// RedirectToActualUrl provides a mock function with given fields: w, r
func (_m *Handler) RedirectToActualUrl(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// RegisterUser provides a mock function with given fields: w, r
func (_m *Handler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateShortUrl provides a mock function with given fields: w, r
func (_m *Handler) UpdateShortUrl(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateUser provides a mock function with given fields: w, r
func (_m *Handler) UpdateUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
